import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Race } from '../Model/race';

export class RaceDataInMemoryServiceService implements InMemoryDbService {
  createDb() { 
    const races = [
      {
          "id": 8,
          "track": "Phillip Island Circui",
          "seasonId": 4,
          "season": null,
          "raceNumber": 1,
          "raceType": 0,
          "raceRows": [
              {
                  "id": 160,
                  "car": "Ferrari 488 GTE",
                  "position": 1,
                  "startPosition": 1,
                  "incidents": 3,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 54,
                  "driver": null
              },
              {
                  "id": 161,
                  "car": "Ford GT - 2017",
                  "position": 2,
                  "startPosition": 4,
                  "incidents": 8,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 55,
                  "driver": null
              },
              {
                  "id": 162,
                  "car": "Ford GT - 2017",
                  "position": 3,
                  "startPosition": 3,
                  "incidents": 4,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 56,
                  "driver": null
              },
              {
                  "id": 163,
                  "car": "Porsche 911 RSR",
                  "position": 4,
                  "startPosition": 2,
                  "incidents": 2,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 57,
                  "driver": null
              },
              {
                  "id": 164,
                  "car": "Ferrari 488 GTE",
                  "position": 5,
                  "startPosition": 5,
                  "incidents": 2,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 58,
                  "driver": null
              },
              {
                  "id": 165,
                  "car": "Porsche 911 RSR",
                  "position": 6,
                  "startPosition": 6,
                  "incidents": 0,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 59,
                  "driver": null
              },
              {
                  "id": 166,
                  "car": "Porsche 911 RSR",
                  "position": 7,
                  "startPosition": 11,
                  "incidents": 12,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 60,
                  "driver": null
              },
              {
                  "id": 167,
                  "car": "Ferrari 488 GTE",
                  "position": 8,
                  "startPosition": 8,
                  "incidents": 2,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 61,
                  "driver": null
              },
              {
                  "id": 168,
                  "car": "Ferrari 488 GTE",
                  "position": 9,
                  "startPosition": 12,
                  "incidents": 3,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 62,
                  "driver": null
              },
              {
                  "id": 169,
                  "car": "Porsche 911 RSR",
                  "position": 10,
                  "startPosition": 9,
                  "incidents": 7,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 63,
                  "driver": null
              },
              {
                  "id": 170,
                  "car": "Ferrari 488 GTE",
                  "position": 11,
                  "startPosition": 10,
                  "incidents": 7,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 64,
                  "driver": null
              },
              {
                  "id": 171,
                  "car": "Porsche 911 RSR",
                  "position": 12,
                  "startPosition": 23,
                  "incidents": 2,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 65,
                  "driver": null
              },
              {
                  "id": 172,
                  "car": "Ferrari 488 GTE",
                  "position": 13,
                  "startPosition": 16,
                  "incidents": 9,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 66,
                  "driver": null
              },
              {
                  "id": 173,
                  "car": "Porsche 911 RSR",
                  "position": 14,
                  "startPosition": 14,
                  "incidents": 9,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 67,
                  "driver": null
              },
              {
                  "id": 174,
                  "car": "Porsche 911 RSR",
                  "position": 15,
                  "startPosition": 28,
                  "incidents": 10,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 68,
                  "driver": null
              },
              {
                  "id": 175,
                  "car": "Porsche 911 RSR",
                  "position": 16,
                  "startPosition": 25,
                  "incidents": 10,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 69,
                  "driver": null
              },
              {
                  "id": 176,
                  "car": "Porsche 911 RSR",
                  "position": 17,
                  "startPosition": 31,
                  "incidents": 2,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 70,
                  "driver": null
              },
              {
                  "id": 177,
                  "car": "Porsche 911 RSR",
                  "position": 18,
                  "startPosition": 21,
                  "incidents": 11,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 71,
                  "driver": null
              },
              {
                  "id": 178,
                  "car": "Porsche 911 RSR",
                  "position": 19,
                  "startPosition": 19,
                  "incidents": 8,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 72,
                  "driver": null
              },
              {
                  "id": 179,
                  "car": "Porsche 911 RSR",
                  "position": 20,
                  "startPosition": 13,
                  "incidents": 13,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 73,
                  "driver": null
              },
              {
                  "id": 180,
                  "car": "Ford GT - 2017",
                  "position": 21,
                  "startPosition": 15,
                  "incidents": 13,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 74,
                  "driver": null
              },
              {
                  "id": 181,
                  "car": "Ferrari 488 GTE",
                  "position": 22,
                  "startPosition": 30,
                  "incidents": 6,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 75,
                  "driver": null
              },
              {
                  "id": 182,
                  "car": "Porsche 911 RSR",
                  "position": 23,
                  "startPosition": 36,
                  "incidents": 16,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 76,
                  "driver": null
              },
              {
                  "id": 183,
                  "car": "Porsche 911 RSR",
                  "position": 24,
                  "startPosition": 29,
                  "incidents": 6,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 77,
                  "driver": null
              },
              {
                  "id": 184,
                  "car": "Porsche 911 RSR",
                  "position": 25,
                  "startPosition": 26,
                  "incidents": 10,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 78,
                  "driver": null
              },
              {
                  "id": 185,
                  "car": "Ford GT - 2017",
                  "position": 26,
                  "startPosition": 53,
                  "incidents": 12,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 79,
                  "driver": null
              },
              {
                  "id": 186,
                  "car": "Ford GT - 2017",
                  "position": 27,
                  "startPosition": 39,
                  "incidents": 8,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 80,
                  "driver": null
              },
              {
                  "id": 187,
                  "car": "Ford GT - 2017",
                  "position": 28,
                  "startPosition": 24,
                  "incidents": 12,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 81,
                  "driver": null
              },
              {
                  "id": 188,
                  "car": "Ferrari 488 GTE",
                  "position": 29,
                  "startPosition": 46,
                  "incidents": 4,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 82,
                  "driver": null
              },
              {
                  "id": 189,
                  "car": "Porsche 911 RSR",
                  "position": 30,
                  "startPosition": 41,
                  "incidents": 3,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 83,
                  "driver": null
              },
              {
                  "id": 190,
                  "car": "Porsche 911 RSR",
                  "position": 31,
                  "startPosition": 40,
                  "incidents": 8,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 84,
                  "driver": null
              },
              {
                  "id": 191,
                  "car": "Porsche 911 RSR",
                  "position": 32,
                  "startPosition": 32,
                  "incidents": 16,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 85,
                  "driver": null
              },
              {
                  "id": 192,
                  "car": "Porsche 911 RSR",
                  "position": 33,
                  "startPosition": 22,
                  "incidents": 12,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 86,
                  "driver": null
              },
              {
                  "id": 193,
                  "car": "Porsche 911 RSR",
                  "position": 34,
                  "startPosition": 50,
                  "incidents": 12,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 87,
                  "driver": null
              },
              {
                  "id": 194,
                  "car": "Ferrari 488 GTE",
                  "position": 35,
                  "startPosition": 42,
                  "incidents": 14,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 88,
                  "driver": null
              },
              {
                  "id": 195,
                  "car": "Porsche 911 RSR",
                  "position": 36,
                  "startPosition": 37,
                  "incidents": 15,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 89,
                  "driver": null
              },
              {
                  "id": 196,
                  "car": "Ferrari 488 GTE",
                  "position": 37,
                  "startPosition": 48,
                  "incidents": 11,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 90,
                  "driver": null
              },
              {
                  "id": 197,
                  "car": "Porsche 911 RSR",
                  "position": 38,
                  "startPosition": 47,
                  "incidents": 18,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 91,
                  "driver": null
              },
              {
                  "id": 198,
                  "car": "Ferrari 488 GTE",
                  "position": 39,
                  "startPosition": 34,
                  "incidents": 8,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 92,
                  "driver": null
              },
              {
                  "id": 199,
                  "car": "Ford GT - 2017",
                  "position": 40,
                  "startPosition": 27,
                  "incidents": 2,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 93,
                  "driver": null
              },
              {
                  "id": 200,
                  "car": "Porsche 911 RSR",
                  "position": 41,
                  "startPosition": 49,
                  "incidents": 11,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 94,
                  "driver": null
              },
              {
                  "id": 201,
                  "car": "Ferrari 488 GTE",
                  "position": 42,
                  "startPosition": 44,
                  "incidents": 11,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 95,
                  "driver": null
              },
              {
                  "id": 202,
                  "car": "Porsche 911 RSR",
                  "position": 43,
                  "startPosition": 18,
                  "incidents": 6,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 96,
                  "driver": null
              },
              {
                  "id": 203,
                  "car": "Ferrari 488 GTE",
                  "position": 44,
                  "startPosition": 33,
                  "incidents": 16,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 97,
                  "driver": null
              },
              {
                  "id": 204,
                  "car": "Porsche 911 RSR",
                  "position": 45,
                  "startPosition": 43,
                  "incidents": 6,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 98,
                  "driver": null
              },
              {
                  "id": 205,
                  "car": "Ford GT - 2017",
                  "position": 46,
                  "startPosition": 51,
                  "incidents": 14,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 99,
                  "driver": null
              },
              {
                  "id": 206,
                  "car": "Porsche 911 RSR",
                  "position": 47,
                  "startPosition": 17,
                  "incidents": 18,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 100,
                  "driver": null
              },
              {
                  "id": 207,
                  "car": "Ferrari 488 GTE",
                  "position": 48,
                  "startPosition": 7,
                  "incidents": 4,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 101,
                  "driver": null
              },
              {
                  "id": 208,
                  "car": "Ferrari 488 GTE",
                  "position": 49,
                  "startPosition": 20,
                  "incidents": 4,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 102,
                  "driver": null
              },
              {
                  "id": 209,
                  "car": "Ferrari 488 GTE",
                  "position": 50,
                  "startPosition": 35,
                  "incidents": 6,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 103,
                  "driver": null
              },
              {
                  "id": 210,
                  "car": "Ferrari 488 GTE",
                  "position": 51,
                  "startPosition": 45,
                  "incidents": 10,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 104,
                  "driver": null
              },
              {
                  "id": 211,
                  "car": "Porsche 911 RSR",
                  "position": 52,
                  "startPosition": 38,
                  "incidents": 6,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 105,
                  "driver": null
              },
              {
                  "id": 212,
                  "car": "Porsche 911 RSR",
                  "position": 53,
                  "startPosition": 52,
                  "incidents": 0,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 8,
                  "driverId": 106,
                  "driver": null
              }
          ]
      },
      {
          "id": 9,
          "track": "Suzuka International Racing Course - Grand Prix",
          "seasonId": 4,
          "season": null,
          "raceNumber": 2,
          "raceType": 2,
          "raceRows": [
              {
                  "id": 213,
                  "car": "Porsche 911 RSR",
                  "position": 1,
                  "startPosition": 1,
                  "incidents": 8,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 57,
                  "driver": null
              },
              {
                  "id": 214,
                  "car": "Porsche 911 RSR",
                  "position": 2,
                  "startPosition": 5,
                  "incidents": 7,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 72,
                  "driver": null
              },
              {
                  "id": 215,
                  "car": "Porsche 911 RSR",
                  "position": 3,
                  "startPosition": 3,
                  "incidents": 6,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 59,
                  "driver": null
              },
              {
                  "id": 216,
                  "car": "Porsche 911 RSR",
                  "position": 4,
                  "startPosition": 4,
                  "incidents": 11,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 78,
                  "driver": null
              },
              {
                  "id": 217,
                  "car": "Ferrari 488 GTE",
                  "position": 5,
                  "startPosition": 8,
                  "incidents": 5,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 102,
                  "driver": null
              },
              {
                  "id": 218,
                  "car": "Porsche 911 RSR",
                  "position": 6,
                  "startPosition": 10,
                  "incidents": 8,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 63,
                  "driver": null
              },
              {
                  "id": 219,
                  "car": "Ferrari 488 GTE",
                  "position": 7,
                  "startPosition": 6,
                  "incidents": 14,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 61,
                  "driver": null
              },
              {
                  "id": 220,
                  "car": "Porsche 911 RSR",
                  "position": 8,
                  "startPosition": 7,
                  "incidents": 9,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 73,
                  "driver": null
              },
              {
                  "id": 221,
                  "car": "Ferrari 488 GTE",
                  "position": 9,
                  "startPosition": 15,
                  "incidents": 16,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 107,
                  "driver": null
              },
              {
                  "id": 222,
                  "car": "Porsche 911 RSR",
                  "position": 10,
                  "startPosition": 12,
                  "incidents": 9,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 85,
                  "driver": null
              },
              {
                  "id": 223,
                  "car": "Porsche 911 RSR",
                  "position": 11,
                  "startPosition": 14,
                  "incidents": 11,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 108,
                  "driver": null
              },
              {
                  "id": 224,
                  "car": "Ford GT - 2017",
                  "position": 12,
                  "startPosition": 21,
                  "incidents": 10,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 79,
                  "driver": null
              },
              {
                  "id": 225,
                  "car": "Ferrari 488 GTE",
                  "position": 13,
                  "startPosition": 20,
                  "incidents": 5,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 66,
                  "driver": null
              },
              {
                  "id": 226,
                  "car": "Ferrari 488 GTE",
                  "position": 14,
                  "startPosition": 13,
                  "incidents": 6,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 75,
                  "driver": null
              },
              {
                  "id": 227,
                  "car": "Porsche 911 RSR",
                  "position": 15,
                  "startPosition": 16,
                  "incidents": 10,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 68,
                  "driver": null
              },
              {
                  "id": 228,
                  "car": "Ferrari 488 GTE",
                  "position": 16,
                  "startPosition": 9,
                  "incidents": 15,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 92,
                  "driver": null
              },
              {
                  "id": 229,
                  "car": "Porsche 911 RSR",
                  "position": 17,
                  "startPosition": 19,
                  "incidents": 6,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 96,
                  "driver": null
              },
              {
                  "id": 230,
                  "car": "Ferrari 488 GTE",
                  "position": 18,
                  "startPosition": 18,
                  "incidents": 7,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 82,
                  "driver": null
              },
              {
                  "id": 231,
                  "car": "Porsche 911 RSR",
                  "position": 19,
                  "startPosition": 23,
                  "incidents": 16,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 71,
                  "driver": null
              },
              {
                  "id": 232,
                  "car": "Porsche 911 RSR",
                  "position": 20,
                  "startPosition": 30,
                  "incidents": 5,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 77,
                  "driver": null
              },
              {
                  "id": 233,
                  "car": "Ford GT - 2017",
                  "position": 21,
                  "startPosition": 17,
                  "incidents": 3,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 93,
                  "driver": null
              },
              {
                  "id": 234,
                  "car": "Ferrari 488 GTE",
                  "position": 22,
                  "startPosition": 28,
                  "incidents": 5,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 103,
                  "driver": null
              },
              {
                  "id": 235,
                  "car": "Ford GT - 2017",
                  "position": 23,
                  "startPosition": 11,
                  "incidents": 6,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 74,
                  "driver": null
              },
              {
                  "id": 236,
                  "car": "Porsche 911 RSR",
                  "position": 24,
                  "startPosition": 26,
                  "incidents": 3,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 69,
                  "driver": null
              },
              {
                  "id": 237,
                  "car": "Ford GT - 2017",
                  "position": 25,
                  "startPosition": 22,
                  "incidents": 15,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 81,
                  "driver": null
              },
              {
                  "id": 238,
                  "car": "Ferrari 488 GTE",
                  "position": 26,
                  "startPosition": 32,
                  "incidents": 15,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 95,
                  "driver": null
              },
              {
                  "id": 239,
                  "car": "Ferrari 488 GTE",
                  "position": 27,
                  "startPosition": 33,
                  "incidents": 9,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 88,
                  "driver": null
              },
              {
                  "id": 240,
                  "car": "Ferrari 488 GTE",
                  "position": 28,
                  "startPosition": 38,
                  "incidents": 15,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 84,
                  "driver": null
              },
              {
                  "id": 241,
                  "car": "Ferrari 488 GTE",
                  "position": 29,
                  "startPosition": 24,
                  "incidents": 17,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 109,
                  "driver": null
              },
              {
                  "id": 242,
                  "car": "Porsche 911 RSR",
                  "position": 30,
                  "startPosition": 37,
                  "incidents": 11,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 87,
                  "driver": null
              },
              {
                  "id": 243,
                  "car": "Porsche 911 RSR",
                  "position": 31,
                  "startPosition": 39,
                  "incidents": 16,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 91,
                  "driver": null
              },
              {
                  "id": 244,
                  "car": "Porsche 911 RSR",
                  "position": 32,
                  "startPosition": 27,
                  "incidents": 11,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 100,
                  "driver": null
              },
              {
                  "id": 245,
                  "car": "Porsche 911 RSR",
                  "position": 33,
                  "startPosition": 40,
                  "incidents": 15,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 65,
                  "driver": null
              },
              {
                  "id": 246,
                  "car": "Ferrari 488 GTE",
                  "position": 34,
                  "startPosition": 2,
                  "incidents": 11,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 64,
                  "driver": null
              },
              {
                  "id": 247,
                  "car": "Porsche 911 RSR",
                  "position": 35,
                  "startPosition": 25,
                  "incidents": 8,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 67,
                  "driver": null
              },
              {
                  "id": 248,
                  "car": "Ferrari 488 GTE",
                  "position": 36,
                  "startPosition": 36,
                  "incidents": 7,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 104,
                  "driver": null
              },
              {
                  "id": 249,
                  "car": "Ford GT - 2017",
                  "position": 37,
                  "startPosition": 35,
                  "incidents": 6,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 110,
                  "driver": null
              },
              {
                  "id": 250,
                  "car": "Ferrari 488 GTE",
                  "position": 38,
                  "startPosition": 41,
                  "incidents": 11,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 111,
                  "driver": null
              },
              {
                  "id": 251,
                  "car": "Porsche 911 RSR",
                  "position": 39,
                  "startPosition": 31,
                  "incidents": 5,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 105,
                  "driver": null
              },
              {
                  "id": 252,
                  "car": "Porsche 911 RSR",
                  "position": 40,
                  "startPosition": 29,
                  "incidents": 7,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 76,
                  "driver": null
              },
              {
                  "id": 253,
                  "car": "Ferrari 488 GTE",
                  "position": 41,
                  "startPosition": 34,
                  "incidents": 4,
                  "points": 0,
                  "infractionPoints": 0,
                  "penaltyPoints": 0,
                  "raceId": 9,
                  "driverId": 112,
                  "driver": null
              }
          ]
      }
  ];
    return {races};
  }
  constructor() { }
}